Algoritmo "Validar-Cartao"


Var
nome, nomeUsuario, senha, senhaUsuario: caractere


Inicio
      nome <- "Eduardo"
      senha <- "paylivre"



      enquanto ((nome <> nomeUsuario) e (senha <> senhaUsuario) ) faca
      escreval("Digite o nome do cartão:")
      leia(nomeUsuario)
      escreval("Digite a senha do cartão:")
      leia(senhaUsuario)
      fimenquanto

      escreval("SEJA BEM-VINDO!")


Fimalgoritmo