Algoritmo "Calcular IMC"
// Lógica de Programação
Var

nome: caractere
peso, altura, imc: real

Inicio

   escreval("Digite o seu nome: ")
   leia(nome)
   escreval("Digite seu peso em Kg: ")
   leia(peso)
   escreval("Digite sua altura em mts: ")
   leia(altura)
   imc <- peso/(altura*altura)
   escreval("Nome: ", nome)
   escreval("Peso: ", peso, " kg")
   escreval("Altura: ", altura, " mts")
   escreval(nome , " seu imc e de " , imc)


Fimalgoritmo